### PR TITLE
remove the dot from s1built.prev.bin

### PR DESCRIPTION
**Pull request by guest123guest**
remove the dot from s1built.prev.bin

### CODE REVIEW

**Comment by Clownacy** [comment]
Using dots as spaces is a pretty common thing in these disassemblies. s2disasm has [chkbitperfect.rev01.bat](https://github.com/sonicretro/s2disasm/blob/master/chkbitperfect.rev01.bat) and [s2.macrosetup.asm](https://github.com/sonicretro/s2disasm/blob/master/s2.macrosetup.asm), for example.

**Comment by guest123guest** [comment]
whats the point?

**Comment by Clownacy** [comment]
It's just the style of whoever made the disassembly, I suppose. Remove the dots, and it becomes harder to tell where one word ends and another begins. You could use spaces, but that would make it trickier to select files with command line tools, where spaces indicate the end of an argument. You could underscores, but (on UK keyboards anyway) that requires more keypresses. You could use camelCase, but maybe the guy that made the disassembly didn't want to use capital letters.

**Comment by guest123guest** [comment]
ok merge first then use add upercase but tell the creator if its ok first

**Comment by Clownacy** [comment]
Assuming it was Hivebrain who named these files, I think he left a long time ago, so I probably can't contact him. Anyhow, for legacy reasons we try not to rename or rearrange files unless absolutely necessary. Guides, and even tools, rely on the original filenames.

**Comment by MainMemory** [comment]
What would we gain by removing the dots anyway? It wouldn't make the filenames more readable, in fact it would make them less readable unless we changed it to underscores/spaces or used camelcase/pascalcase/whatever, and at that point we're just trading one naming system for another, when the one we have works perfectly fine.

**Comment by guest123guest** [comment]
ok

**Pull request closed without merging**
