### PR TITLE
a message to you

### PR DESCRIPTION
**Pull request by 720bonelesskickflip**

### CODE REVIEW

**Comment by Clownacy** [comment]
I can either play along and lament how this makes me regret ever making those Elemental Shield videos, or I can just be honest and say this makes me want to make more Element Shield videos.

I do wonder who this could be. Someone who knows about invalid asm68k opcodes and how wrong it is to call the Z80 stops 'useless' must know their stuff. Heck, I'd almost claim this was Markey, if not for the fact he was name-dropped. Then again, maybe that was deliberately to throw us off his track... Or maybe the whole point of name-dropping him was to make us suspect it was him.

My money's on Natsumi.

**Comment by 720bonelesskickflip** [comment]
i do not know what you are talking about. what do you mean asm68k opcodes? i didnt use them you troll.

**Comment by 720bonelesskickflip** [comment]
this new change deletes the entire disassembly. screw you you insulting troll i hope you feel sorry.

**Comment by flamewing** [comment]
And that is it. You are gone.

**Comment by NatsumiFox** [comment]
I'd take credit Clownacy but honestly I don't have the pure genius of this person backing me. Sorry =P

**Pull request closed without merging**
